(function () {
  'use strict';
  const isApp = location.hostname === 'app.teamdeck.space' || /(^|\.)teamdeck-app-preview\.pages\.dev$/i.test(location.hostname);
  if (!isApp) return;
  const state = { organization: null, departments: [], employees: [], audit: [], access: null };
  const appShell = () => document.querySelector('.app');
  const request = (path, options = {}) => fetch(path, { credentials: 'include', cache: 'no-store', ...options }).then(async response => { const data = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(data.error || 'Не удалось загрузить данные App'); error.code = data.code; error.status = response.status; throw error; } return data; });
  function hideAppShell() { appShell()?.style.setProperty('display', 'none', 'important'); }
  function showAppShell() { document.documentElement.classList.remove('app-environment'); appShell()?.style.removeProperty('display'); }
  function resetEmptyDashboard() { const dashboard = document.getElementById('dashboard'); if (!dashboard) return; dashboard.querySelectorAll('.kpi .num').forEach(node => { node.textContent = '0'; }); dashboard.querySelectorAll('.dashboard-table tbody').forEach(node => { node.innerHTML = '<tr><td colspan="4" class="empty-state">Пока нет событий</td></tr>'; }); dashboard.querySelectorAll('.activity-list,.dashboard-activity-list').forEach(node => { node.innerHTML = '<div class="empty-state">Пока нет активности</div>'; }); }
  function escapeHtml(value) { return String(value || '').replace(/[&<>\"']/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;' }[char])); }
  function toCompanyDepartment(item) { return { id: item.id, name: item.name, lead: '', color: '#0658F6', short: item.name.slice(0, 2).toUpperCase() }; }
  function toCompanyPerson(item) { return { id: item.id, name: `${item.first_name} ${item.last_name}`, role: item.job_title || 'Сотрудник', department: item.department_name || '', manager: '', email: item.email || '', phone: item.phone || '', photo: item.avatar_url || '', status: item.status === 'active' ? 'Штатный сотрудник' : item.status, startDate: item.hired_at || '', workMode: '', source: 'App', addedAt: Date.parse(item.created_at || '') || Date.now(), serverId: item.id }; }
  function apply(data) { Object.assign(state, data); resetEmptyDashboard(); showAppShell(); window.teamdeckAppData = state; if (Array.isArray(data.departments) && typeof companyDepartments !== 'undefined') { companyDepartments = data.departments.map(toCompanyDepartment); companyPeople = (data.employees || []).map(toCompanyPerson); if (typeof window.renderCompanyTeam === 'function') window.renderCompanyTeam(); } document.documentElement.dataset.appReady = 'true'; window.dispatchEvent(new CustomEvent('teamdeck:app-data', { detail: state })); }
  function setError(message) { const node = document.getElementById('appAccessError'); if (node) node.textContent = message || ''; }
  function formData() { return { name: document.getElementById('appOrgName').value.trim(), legalName: document.getElementById('appOrgName').value.trim(), inn: document.getElementById('appOrgInn').value.trim(), ogrn: document.getElementById('appOrgOgrn').value.trim(), legalAddress: document.getElementById('appOrgAddress').value.trim() }; }
  function showSetupGate() {
    hideAppShell(); if (document.getElementById('appAccessGate')) return;
    const gate = document.createElement('section'); gate.id = 'appAccessGate'; gate.className = 'app-access-gate';
    gate.innerHTML = `<div class="app-access-card"><div class="app-access-brand"><img src="assets/teamdeck-logo.png" alt="Teamdeck"></div><h1>Настройте рабочее пространство</h1><form id="appOrgForm"><div class="app-form-grid"><div class="app-field-with-action"><label>ИНН<input id="appOrgInn" inputmode="numeric" maxlength="12" placeholder="10 или 12 цифр" required></label><button class="btn app-inline-btn" id="appLookupInn" type="button">Найти организацию</button></div><label class="wide">Название организации<input id="appOrgName" required></label><label>ОГРНИП<input id="appOrgOgrn" inputmode="numeric" maxlength="15"></label><label>Юридический адрес<input id="appOrgAddress" required></label></div><div id="appLookupResult" class="app-access-hint"></div><div id="appEmailStatus" class="app-access-hint"></div><div id="appAccessError" class="app-access-error" role="alert"></div><div class="app-access-actions"><button class="btn primary" id="appCreateOrg" type="submit" disabled>Создать организацию</button><button class="btn app-logout-btn" id="appAccessLogout" type="button">Выйти</button></div></form><section class="app-plan-stage" id="appPlanStage" hidden><h2>Выберите тариф</h2><p>Тарифы «Старт» и «Бизнес» доступны бесплатно в течение 7 дней. Enterprise подключается по запросу.</p><div class="app-plan-grid" id="appPlanGrid"></div><div id="appPlanStatus" class="app-access-hint"></div></section></div>`;
    document.body.appendChild(gate);
    const lookupButton = document.getElementById('appLookupInn'); const createButton = document.getElementById('appCreateOrg'); const syncCreateButton = () => { createButton.disabled = !document.getElementById('appOrgInn').value.trim() || !document.getElementById('appOrgName').value.trim() || !document.getElementById('appOrgAddress').value.trim(); }; lookupButton.addEventListener('click', event => { event.preventDefault(); lookupInn(); }); document.getElementById('appOrgForm').addEventListener('submit', createOrganization); ['appOrgInn','appOrgName','appOrgAddress'].forEach(id => document.getElementById(id).addEventListener('input', syncCreateButton)); syncCreateButton(); document.getElementById('appAccessLogout').onclick = () => typeof logoutUser === 'function' && logoutUser();
  }
  async function lookupInn() { const inn = document.getElementById('appOrgInn').value.trim(); const result = document.getElementById('appLookupResult'); result.textContent = 'Ищем организацию…'; try { const data = await request('/api/app/company-lookup?inn=' + encodeURIComponent(inn)); const first = data.results?.[0]; if (!first) { result.textContent = 'Организация не найдена.'; return; } document.getElementById('appOrgName').value = first.name || ''; document.getElementById('appOrgOgrn').value = first.ogrn || ''; document.getElementById('appOrgAddress').value = first.address || ''; document.getElementById('appOrgAddress').dispatchEvent(new Event('input')); result.textContent = `Найдено: ${first.name}. Статус: ${first.status || 'не указан'}.`; } catch (error) { result.textContent = error.message; } }
  async function sendEmailCode() { const email = document.getElementById('appBillingEmail').value.trim(); const status = document.getElementById('appEmailStatus'); status.textContent = 'Отправляем код…'; try { const data = await request('/api/app/billing-email', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email }) }); document.getElementById('appEmailCodeRow').hidden = false; status.textContent = data.message || `Код подтверждения отправлен на ${email}`; } catch (error) { status.textContent = error.message; } }
  async function verifyEmailCode() { const email = document.getElementById('appBillingEmail').value.trim(); const code = document.getElementById('appEmailCode').value.trim(); try { await request('/api/app/billing-email', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, code }) }); document.getElementById('appEmailStatus').innerHTML = '<span class="app-verified">✓</span> Почта подтверждена'; document.getElementById('appEmailCodeRow').hidden = true; document.getElementById('appSendCode').disabled = true; document.getElementById('appBillingEmail').disabled = true; } catch (error) { document.getElementById('appEmailStatus').innerHTML = '<span class="app-invalid">×</span> Код неверный'; setError(error.message || 'Код неверный'); } }
  async function createOrganization(event) { event.preventDefault(); setError(''); const data = formData(); try { const result = await request('/api/app/organizations', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(data) }); gateAfterOrganization(result.id, data); } catch (error) { setError(error.message); } }
  async function gateAfterOrganization(organizationId, data) { document.getElementById('appOrgForm').hidden = true; const stage = document.getElementById('appPlanStage'); stage.hidden = false; const plans = await request('/api/app/plans'); document.getElementById('appPlanGrid').innerHTML = (plans.plans || []).map(plan => `<button class="app-plan-card" type="button" data-plan-id="${escapeHtml(plan.id)}" data-plan-code="${escapeHtml(plan.code)}"><b>${escapeHtml(plan.name)}</b><span>${plan.code === 'enterprise' ? 'По запросу' : '7 дней бесплатно'}</span><small>${plan.max_employees ? `До ${plan.max_employees} сотрудников` : 'Индивидуальные условия'}</small></button>`).join(''); document.querySelectorAll('.app-plan-card').forEach(button => { button.onclick = () => activatePlan(organizationId, data, button.dataset.planId, button.dataset.planCode); }); }
  async function activatePlan(organizationId, data, planId, planCode) { const status = document.getElementById('appPlanStatus'); status.textContent = 'Сохраняем выбор…'; try { if (planCode === 'enterprise') { const invoice = await request('/api/app/invoices', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ planId, ...data }) }); status.textContent = `Заявка на счёт ${invoice.number} создана и отправлена на ${invoice.billingEmail}.`; return; } await request('/api/app/organizations', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ organizationId, planId, billingEmail: data.billingEmail }) }); status.textContent = 'Тариф активирован. Загружаем рабочее пространство…'; setTimeout(() => location.reload(), 700); } catch (error) { status.textContent = error.message; } }
  async function load() { apply(await request('/api/app/bootstrap')); return state; }
  window.teamdeckApp = { state, request, load, createDepartment: data => request('/api/app/departments', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(data) }), createEmployee: data => request('/api/app/employees', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(data) }) };
  function showLoadError(error) { hideAppShell(); let node = document.getElementById('appLoadError'); if (!node) { node = document.createElement('section'); node.id = 'appLoadError'; node.className = 'app-load-error'; node.innerHTML = '<div><img src="assets/teamdeck-logo.png" alt="Teamdeck"><h1>Не удалось открыть рабочее пространство</h1><p></p><button class="btn primary" type="button">Повторить</button></div>'; document.body.appendChild(node); node.querySelector('button').onclick = () => { node.remove(); start(); }; } node.querySelector('p').textContent = error?.message || 'Проверьте соединение и повторите попытку.'; }
  async function start() { try { await load(); } catch (error) { if (error.code === 'APP_ACCESS_REQUIRED' || error.status === 401 || error.status === 403) showSetupGate(); else { console.warn('[teamdeck-app]', error.message); showLoadError(error); } } }
  hideAppShell(); window.addEventListener('teamdeck:authenticated', start); if (document.readyState === 'loading') window.addEventListener('DOMContentLoaded', start, { once: true }); else start();
})();
