(function () {
  'use strict';
  const isApp = location.hostname === 'app.teamdeck.space' || /(^|\.)teamdeck-app-preview\.pages\.dev$/i.test(location.hostname);
  if (!isApp) return;
  const state = { organization: null, departments: [], employees: [], audit: [], access: null };
  const appShell = () => document.querySelector('.app');
  const request = (path, options = {}) => fetch(path, { credentials: 'include', cache: 'no-store', ...options }).then(async response => { const data = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(data.error || 'Не удалось загрузить данные App'); error.code = data.code; error.status = response.status; throw error; } return data; });
  function hideAppShell() { appShell()?.style.setProperty('display', 'none', 'important'); }
  function showAppShell() { appShell()?.style.removeProperty('display'); }
  function escapeHtml(value) { return String(value || '').replace(/[&<>\"']/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;' }[char])); }
  function toCompanyDepartment(item) { return { id: item.id, name: item.name, lead: '', color: '#0658F6', short: item.name.slice(0, 2).toUpperCase() }; }
  function toCompanyPerson(item) { return { id: item.id, name: `${item.first_name} ${item.last_name}`, role: item.job_title || 'Сотрудник', department: item.department_name || '', manager: '', email: item.email || '', phone: item.phone || '', photo: item.avatar_url || '', status: item.status === 'active' ? 'Штатный сотрудник' : item.status, startDate: item.hired_at || '', workMode: '', source: 'App', addedAt: Date.parse(item.created_at || '') || Date.now(), serverId: item.id }; }
  function apply(data) { Object.assign(state, data); showAppShell(); window.teamdeckAppData = state; if (Array.isArray(data.departments) && typeof companyDepartments !== 'undefined') { companyDepartments = data.departments.map(toCompanyDepartment); companyPeople = (data.employees || []).map(toCompanyPerson); if (typeof window.renderCompanyTeam === 'function') window.renderCompanyTeam(); } document.documentElement.dataset.appReady = 'true'; window.dispatchEvent(new CustomEvent('teamdeck:app-data', { detail: state })); }
  function setError(message) { const node = document.getElementById('appAccessError'); if (node) node.textContent = message || ''; }
  function formData() { return { name: document.getElementById('appOrgName').value.trim(), legalName: document.getElementById('appOrgName').value.trim(), inn: document.getElementById('appOrgInn').value.trim(), kpp: document.getElementById('appOrgKpp').value.trim(), legalAddress: document.getElementById('appOrgAddress').value.trim(), billingEmail: document.getElementById('appBillingEmail').value.trim().toLowerCase() }; }
  function showSetupGate() {
    hideAppShell(); if (document.getElementById('appAccessGate')) return;
    const gate = document.createElement('section'); gate.id = 'appAccessGate'; gate.className = 'app-access-gate';
    gate.innerHTML = `<div class="app-access-card"><div class="app-access-brand"><img src="assets/teamdeck-logo.png" alt="Teamdeck"></div><h1>Настройте рабочее пространство</h1><p class="app-access-lead">Укажите данные компании и подтвердите почту для выставления счёта.</p><form id="appOrgForm"><div class="app-form-grid"><div class="app-field-with-action"><label>ИНН<input id="appOrgInn" inputmode="numeric" maxlength="12" placeholder="10 или 12 цифр" required></label><button class="btn app-inline-btn" id="appLookupInn" type="button">Найти организацию</button></div><label class="wide">Название организации<input id="appOrgName" required></label><label>КПП<input id="appOrgKpp" inputmode="numeric" maxlength="9"></label><label>Юридический адрес<input id="appOrgAddress"></label><div class="app-field-with-action wide"><label>Почта для выставления счёта<input id="appBillingEmail" type="email" required></label><button class="btn app-inline-btn" id="appSendCode" type="button" hidden>Отправить код</button></div><div class="app-field-with-action wide app-code-row" id="appEmailCodeRow" hidden><label>Код подтверждения<input id="appEmailCode" inputmode="numeric" maxlength="6" placeholder="6 цифр"></label><button class="btn app-inline-btn" id="appVerifyCode" type="button">Подтвердить</button></div><div class="app-field wide app-trial-hint"><label>Тариф<div class="app-plan-placeholder">Выбор тарифа — следующим шагом</div></label></div></div><div id="appLookupResult" class="app-access-hint"></div><div id="appEmailStatus" class="app-access-hint"></div><div id="appAccessError" class="app-access-error" role="alert"></div><div class="app-access-actions"><button class="btn primary" type="submit">Создать организацию</button><button class="btn app-logout-btn" id="appAccessLogout" type="button">Выйти</button></div></form><section class="app-plan-stage" id="appPlanStage" hidden><h2>Выберите тариф</h2><p>Тарифы «Старт» и «Бизнес» доступны бесплатно в течение 7 дней. Enterprise подключается по запросу.</p><div class="app-plan-grid" id="appPlanGrid"></div><div id="appPlanStatus" class="app-access-hint"></div></section></div>`;
    document.body.appendChild(gate);
    document.getElementById('appBillingEmail').value = localStorage.getItem('teamdeck-auth-email') || '';
    document.getElementById('appLookupInn').onclick = lookupInn; document.getElementById('appSendCode').onclick = sendEmailCode; document.getElementById('appVerifyCode').onclick = verifyEmailCode; document.getElementById('appBillingEmail').addEventListener('input', event => { document.getElementById('appSendCode').hidden = !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(event.target.value.trim()); }); document.getElementById('appOrgForm').onsubmit = createOrganization; document.getElementById('appAccessLogout').onclick = () => typeof logoutUser === 'function' && logoutUser();
  }
  async function lookupInn() { const inn = document.getElementById('appOrgInn').value.trim(); const result = document.getElementById('appLookupResult'); result.textContent = 'Ищем организацию…'; try { const data = await request('/api/app/company-lookup?inn=' + encodeURIComponent(inn)); const first = data.results?.[0]; if (!first) { result.textContent = 'Организация не найдена.'; return; } document.getElementById('appOrgName').value = first.name || ''; document.getElementById('appOrgKpp').value = first.kpp || ''; document.getElementById('appOrgAddress').value = first.address || ''; result.textContent = `Найдено: ${first.name}. Статус: ${first.status || 'не указан'}.`; } catch (error) { result.textContent = error.message; } }
  async function sendEmailCode() { const email = document.getElementById('appBillingEmail').value.trim(); const status = document.getElementById('appEmailStatus'); status.textContent = 'Отправляем код…'; try { const data = await request('/api/app/billing-email', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email }) }); document.getElementById('appEmailCodeRow').hidden = false; status.textContent = data.message || `Код подтверждения отправлен на ${email}`; } catch (error) { status.textContent = error.message; } }
  async function verifyEmailCode() { const email = document.getElementById('appBillingEmail').value.trim(); const code = document.getElementById('appEmailCode').value.trim(); try { await request('/api/app/billing-email', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, code }) }); document.getElementById('appEmailStatus').innerHTML = '<span class="app-verified">✓</span> Почта подтверждена'; document.getElementById('appEmailCodeRow').hidden = true; document.getElementById('appSendCode').hidden = true; document.getElementById('appBillingEmail').disabled = true; } catch (error) { setError(error.message); } }
  async function createOrganization(event) { event.preventDefault(); setError(''); const data = formData(); try { const result = await request('/api/app/organizations', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(data) }); gateAfterOrganization(result.id, data); } catch (error) { setError(error.message); } }
  async function gateAfterOrganization(organizationId, data) { document.getElementById('appOrgForm').hidden = true; const stage = document.getElementById('appPlanStage'); stage.hidden = false; const plans = await request('/api/app/plans'); document.getElementById('appPlanGrid').innerHTML = (plans.plans || []).map(plan => `<button class="app-plan-card" type="button" data-plan-id="${escapeHtml(plan.id)}" data-plan-code="${escapeHtml(plan.code)}"><b>${escapeHtml(plan.name)}</b><span>${plan.code === 'enterprise' ? 'По запросу' : '7 дней бесплатно'}</span><small>${plan.max_employees ? `До ${plan.max_employees} сотрудников` : 'Индивидуальные условия'}</small></button>`).join(''); document.querySelectorAll('.app-plan-card').forEach(button => { button.onclick = () => activatePlan(organizationId, data, button.dataset.planId, button.dataset.planCode); }); }
  async function activatePlan(organizationId, data, planId, planCode) { const status = document.getElementById('appPlanStatus'); status.textContent = 'Сохраняем выбор…'; try { if (planCode === 'enterprise') { const invoice = await request('/api/app/invoices', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ planId, ...data }) }); status.textContent = `Заявка на счёт ${invoice.number} создана и отправлена на ${invoice.billingEmail}.`; return; } await request('/api/app/organizations', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ organizationId, planId, billingEmail: data.billingEmail }) }); status.textContent = 'Тариф активирован. Загружаем рабочее пространство…'; setTimeout(() => location.reload(), 700); } catch (error) { status.textContent = error.message; } }
  async function load() { apply(await request('/api/app/bootstrap')); return state; }
  window.teamdeckApp = { state, request, load, createDepartment: data => request('/api/app/departments', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(data) }), createEmployee: data => request('/api/app/employees', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(data) }) };
  async function start() { try { await load(); } catch (error) { if (error.code === 'APP_ACCESS_REQUIRED' || error.status === 401 || error.status === 403) showSetupGate(); else { hideAppShell(); console.warn('[teamdeck-app]', error.message); } } }
  hideAppShell(); window.addEventListener('teamdeck:authenticated', start); window.addEventListener('DOMContentLoaded', start);
})();
